target 'LPAlert', :exclusive => true do
  pod "LPAlert", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "LPAlert", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  pod 'ACPButton'
end
